
spring.application.name=notification_system

# Supabase Database
spring.datasource.url=jdbc:postgresql://${SUPABASE_DB_HOST:aws-0-ap-northeast-1.pooler.supabase.com}:${SUPABASE_DB_PORT:6543}/${SUPABASE_DB_NAME:postgres}?prepareThreshold=0
spring.datasource.username=${SUPABASE_DB_USERNAME}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.show-sql=false

# Supabase Security / JWKS
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SUPABASE_JWKS_URL:https://kyqgjdhgxrkguvslphvm.supabase.co/auth/v1/.well-known/jwks.json}
supabase.url=${SUPABASE_URL:https://kyqgjdhgxrkguvslphvm.supabase.co}
supabase.publishable-key=${SUPABASE_PUBLISHABLE_KEY}
supabase.secret-key=${SUPABASE_SECRET_KEY}

# RabbitMQ / CloudAMQP
spring.rabbitmq.addresses=${CLOUDAMQP_URL}
spring.rabbitmq.listener.simple.acknowledge-mode=manual

# Resend / Mail
resend.api-key=${RESEND_API_KEY}
resend.from-email=onboarding@resend.dev
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=notifications@yourtestapp.com

# Twilio SMS
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.phone-number=${TWILIO_PHONE_NUMBER}
fast2sms.api-key=${FAST2SMS_API_KEY}